apiVersion: apps/v1
kind: Deployment
metadata:
  name:  open-bank-beneficiary-adminer
spec:
  selector:
    matchLabels:
      app: open-bank-beneficiary-adminer
  replicas: 1
  template:
    metadata:
      labels:
        app: open-bank-beneficiary-adminer
    spec:
      restartPolicy: Always
      containers:
        - name: open-bank-beneficiary-adminer
          image: adminer:4
          #imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: open-bank-beneficiary-adminer
spec:
  selector:
    app: open-bank-beneficiary-adminer
  ports:
    - name: http
      port: 8082
      targetPort: 8080
  type: ClusterIP