apiVersion: apps/v1
kind: Deployment
metadata:
  name:  open-bank-beneficiary-db
spec:
  selector:
    matchLabels:
      app: open-bank-beneficiary-db
  replicas: 1
  template:
    metadata:
      labels:
        app: open-bank-beneficiary-db
    spec:
      containers:
        - name: open-bank-beneficiary-db
          image: postgres:12.4-alpine
          #imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: open-bank-beneficiary
            - name: POSTGRES_PASSWORD
              value: secret

---
apiVersion: v1
kind: Service
metadata:
  name: open-bank-beneficiary-db
spec:
  selector:
    app: open-bank-beneficiary-db
  ports:
    - name: http
      port: 5432
      targetPort: 5432
  type: ClusterIP
