/*
 * Beneficiary
 * The beneficiaries resource is used by an AISP to retrieve the account beneficiaries information for a specific AccountId or to retrieve the beneficiaries information in bulk for account(s) that the PSU has authorised to access.
 *
 * OpenAPI spec version: 3.1.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Mate model module.
 * @module model/Mate
 * @version 3.1.7
 */
export class Mate {
  /**
   * Constructs a new <code>Mate</code>.
   * @alias module:model/Mate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Mate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Mate} obj Optional instance to populate.
   * @return {module:model/Mate} The populated <code>Mate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Mate();
      if (data.hasOwnProperty('totalPage'))
        obj.totalPage = ApiClient.convertToType(data['totalPage'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} totalPage
 */
Mate.prototype.totalPage = undefined;

