/*
 * Beneficiary
 * The beneficiaries resource is used by an AISP to retrieve the account beneficiaries information for a specific AccountId or to retrieve the beneficiaries information in bulk for account(s) that the PSU has authorised to access.
 *
 * OpenAPI spec version: 3.1.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class OBBeneficiaryType1Code.
 * @enum {String}
 * @readonly
 */
const OBBeneficiaryType1Code = {
  /**
   * value: "Ordinary"
   * @const
   */
  ordinary: "Ordinary",

  /**
   * value: "Trusted"
   * @const
   */
  trusted: "Trusted",

  /**
   * Returns a <code>OBBeneficiaryType1Code</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/OBBeneficiaryType1Code} The enum <code>OBBeneficiaryType1Code</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {OBBeneficiaryType1Code};