/*
 * Beneficiary
 * The beneficiaries resource is used by an AISP to retrieve the account beneficiaries information for a specific AccountId or to retrieve the beneficiaries information in bulk for account(s) that the PSU has authorised to access.
 *
 * OpenAPI spec version: 3.1.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OBBeneficiaryType1Code} from './OBBeneficiaryType1Code';
import {OBBranchAndFinancialInstitutionIdentification6} from './OBBranchAndFinancialInstitutionIdentification6';
import {OBCashAccount5} from './OBCashAccount5';
import {OBSupplementaryData1} from './OBSupplementaryData1';

/**
 * The OBBeneficiary5 model module.
 * @module model/OBBeneficiary5
 * @version 3.1.7
 */
export class OBBeneficiary5 {
  /**
   * Constructs a new <code>OBBeneficiary5</code>.
   * @alias module:model/OBBeneficiary5
   * @class
   * @param accountId {String} 
   * @param beneficiaryId {String} 
   */
  constructor(accountId, beneficiaryId) {
    this.accountId = accountId;
    this.beneficiaryId = beneficiaryId;
  }

  /**
   * Constructs a <code>OBBeneficiary5</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OBBeneficiary5} obj Optional instance to populate.
   * @return {module:model/OBBeneficiary5} The populated <code>OBBeneficiary5</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OBBeneficiary5();
      if (data.hasOwnProperty('accountId'))
        obj.accountId = ApiClient.convertToType(data['accountId'], 'String');
      if (data.hasOwnProperty('beneficiaryId'))
        obj.beneficiaryId = ApiClient.convertToType(data['beneficiaryId'], 'String');
      if (data.hasOwnProperty('beneficiaryType'))
        obj.beneficiaryType = OBBeneficiaryType1Code.constructFromObject(data['beneficiaryType']);
      if (data.hasOwnProperty('creditorAccount'))
        obj.creditorAccount = OBCashAccount5.constructFromObject(data['creditorAccount']);
      if (data.hasOwnProperty('creditorAgent'))
        obj.creditorAgent = OBBranchAndFinancialInstitutionIdentification6.constructFromObject(data['creditorAgent']);
      if (data.hasOwnProperty('reference'))
        obj.reference = ApiClient.convertToType(data['reference'], 'String');
      if (data.hasOwnProperty('supplementaryData'))
        obj.supplementaryData = OBSupplementaryData1.constructFromObject(data['supplementaryData']);
    }
    return obj;
  }
}

/**
 * @member {String} accountId
 */
OBBeneficiary5.prototype.accountId = undefined;

/**
 * @member {String} beneficiaryId
 */
OBBeneficiary5.prototype.beneficiaryId = undefined;

/**
 * @member {module:model/OBBeneficiaryType1Code} beneficiaryType
 */
OBBeneficiary5.prototype.beneficiaryType = undefined;

/**
 * @member {module:model/OBCashAccount5} creditorAccount
 */
OBBeneficiary5.prototype.creditorAccount = undefined;

/**
 * @member {module:model/OBBranchAndFinancialInstitutionIdentification6} creditorAgent
 */
OBBeneficiary5.prototype.creditorAgent = undefined;

/**
 * @member {String} reference
 */
OBBeneficiary5.prototype.reference = undefined;

/**
 * @member {module:model/OBSupplementaryData1} supplementaryData
 */
OBBeneficiary5.prototype.supplementaryData = undefined;

