/*
 * Beneficiary
 * The beneficiaries resource is used by an AISP to retrieve the account beneficiaries information for a specific AccountId or to retrieve the beneficiaries information in bulk for account(s) that the PSU has authorised to access.
 *
 * OpenAPI spec version: 3.1.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OBExternalFinancialInstitutionIdentification4Code} from './OBExternalFinancialInstitutionIdentification4Code';
import {OBPostalAddress6} from './OBPostalAddress6';

/**
 * The OBBranchAndFinancialInstitutionIdentification6 model module.
 * @module model/OBBranchAndFinancialInstitutionIdentification6
 * @version 3.1.7
 */
export class OBBranchAndFinancialInstitutionIdentification6 {
  /**
   * Constructs a new <code>OBBranchAndFinancialInstitutionIdentification6</code>.
   * @alias module:model/OBBranchAndFinancialInstitutionIdentification6
   * @class
   * @param identification {String} 
   */
  constructor(identification) {
    this.identification = identification;
  }

  /**
   * Constructs a <code>OBBranchAndFinancialInstitutionIdentification6</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OBBranchAndFinancialInstitutionIdentification6} obj Optional instance to populate.
   * @return {module:model/OBBranchAndFinancialInstitutionIdentification6} The populated <code>OBBranchAndFinancialInstitutionIdentification6</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OBBranchAndFinancialInstitutionIdentification6();
      if (data.hasOwnProperty('identification'))
        obj.identification = ApiClient.convertToType(data['identification'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('postalAddress'))
        obj.postalAddress = OBPostalAddress6.constructFromObject(data['postalAddress']);
      if (data.hasOwnProperty('schemeName'))
        obj.schemeName = OBExternalFinancialInstitutionIdentification4Code.constructFromObject(data['schemeName']);
    }
    return obj;
  }
}

/**
 * @member {String} identification
 */
OBBranchAndFinancialInstitutionIdentification6.prototype.identification = undefined;

/**
 * @member {String} name
 */
OBBranchAndFinancialInstitutionIdentification6.prototype.name = undefined;

/**
 * @member {module:model/OBPostalAddress6} postalAddress
 */
OBBranchAndFinancialInstitutionIdentification6.prototype.postalAddress = undefined;

/**
 * @member {module:model/OBExternalFinancialInstitutionIdentification4Code} schemeName
 */
OBBranchAndFinancialInstitutionIdentification6.prototype.schemeName = undefined;

