/*
 * Beneficiary
 * The beneficiaries resource is used by an AISP to retrieve the account beneficiaries information for a specific AccountId or to retrieve the beneficiaries information in bulk for account(s) that the PSU has authorised to access.
 *
 * OpenAPI spec version: 3.1.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OBExternalAccountIdentification4Code} from './OBExternalAccountIdentification4Code';

/**
 * The OBCashAccount5 model module.
 * @module model/OBCashAccount5
 * @version 3.1.7
 */
export class OBCashAccount5 {
  /**
   * Constructs a new <code>OBCashAccount5</code>.
   * @alias module:model/OBCashAccount5
   * @class
   * @param identification {String} 
   * @param schemeName {module:model/OBExternalAccountIdentification4Code} 
   */
  constructor(identification, schemeName) {
    this.identification = identification;
    this.schemeName = schemeName;
  }

  /**
   * Constructs a <code>OBCashAccount5</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OBCashAccount5} obj Optional instance to populate.
   * @return {module:model/OBCashAccount5} The populated <code>OBCashAccount5</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OBCashAccount5();
      if (data.hasOwnProperty('identification'))
        obj.identification = ApiClient.convertToType(data['identification'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('schemeName'))
        obj.schemeName = OBExternalAccountIdentification4Code.constructFromObject(data['schemeName']);
      if (data.hasOwnProperty('secondaryIdentification'))
        obj.secondaryIdentification = ApiClient.convertToType(data['secondaryIdentification'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} identification
 */
OBCashAccount5.prototype.identification = undefined;

/**
 * @member {String} name
 */
OBCashAccount5.prototype.name = undefined;

/**
 * @member {module:model/OBExternalAccountIdentification4Code} schemeName
 */
OBCashAccount5.prototype.schemeName = undefined;

/**
 * @member {String} secondaryIdentification
 */
OBCashAccount5.prototype.secondaryIdentification = undefined;

