/*
 * Beneficiary
 * The beneficiaries resource is used by an AISP to retrieve the account beneficiaries information for a specific AccountId or to retrieve the beneficiaries information in bulk for account(s) that the PSU has authorised to access.
 *
 * OpenAPI spec version: 3.1.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OBBeneficiary5} from './OBBeneficiary5';

/**
 * The OBReadDataBeneficiary5 model module.
 * @module model/OBReadDataBeneficiary5
 * @version 3.1.7
 */
export class OBReadDataBeneficiary5 {
  /**
   * Constructs a new <code>OBReadDataBeneficiary5</code>.
   * @alias module:model/OBReadDataBeneficiary5
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OBReadDataBeneficiary5</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OBReadDataBeneficiary5} obj Optional instance to populate.
   * @return {module:model/OBReadDataBeneficiary5} The populated <code>OBReadDataBeneficiary5</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OBReadDataBeneficiary5();
      if (data.hasOwnProperty('beneficiary'))
        obj.beneficiary = ApiClient.convertToType(data['beneficiary'], [OBBeneficiary5]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/OBBeneficiary5>} beneficiary
 */
OBReadDataBeneficiary5.prototype.beneficiary = undefined;

