/*
 * Beneficiary
 * The beneficiaries resource is used by an AISP to retrieve the account beneficiaries information for a specific AccountId or to retrieve the beneficiaries information in bulk for account(s) that the PSU has authorised to access.
 *
 * OpenAPI spec version: 3.1.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Mate} from './Mate';
import {OBReadDataBeneficiary5} from './OBReadDataBeneficiary5';

/**
 * The OBReadBeneficiary5 model module.
 * @module model/OBReadBeneficiary5
 * @version 3.1.7
 */
export class OBReadBeneficiary5 {
  /**
   * Constructs a new <code>OBReadBeneficiary5</code>.
   * @alias module:model/OBReadBeneficiary5
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OBReadBeneficiary5</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OBReadBeneficiary5} obj Optional instance to populate.
   * @return {module:model/OBReadBeneficiary5} The populated <code>OBReadBeneficiary5</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OBReadBeneficiary5();
      if (data.hasOwnProperty('data'))
        obj.data = OBReadDataBeneficiary5.constructFromObject(data['data']);
      if (data.hasOwnProperty('mate'))
        obj.mate = Mate.constructFromObject(data['mate']);
    }
    return obj;
  }
}

/**
 * @member {module:model/OBReadDataBeneficiary5} data
 */
OBReadBeneficiary5.prototype.data = undefined;

/**
 * @member {module:model/Mate} mate
 */
OBReadBeneficiary5.prototype.mate = undefined;

